#To create secret on the command line, run "kubectl create secret generic mysql-pass --from-literal=password=devdb@123"
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
stringData:
  password: devdb@123
