apiVersion: v1
kind: Service
metadata:  
  name: wordpress-service
spec:
  selector:    
    app: wordpress
    tier: frontend
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
